### ISSUE TITLE
沙特阿拉伯 和 阿联酋的 geojson 包含吗？

### ISSUE THREAD

**Issue by hexxv** [Surbowl/world-geo-json-zh#12]
沙特阿拉伯 和 阿联酋的 geojson 包含吗？

**Comment by Surbowl** [comment]
包含的
https://github.com/Surbowl/world-geo-json-zh/blob/2d398901d3ce4ba7792ef03395b29e7b6a6cf4c7/world.zh.json#L68
https://github.com/Surbowl/world-geo-json-zh/blob/2d398901d3ce4ba7792ef03395b29e7b6a6cf4c7/world.zh.json#L34

**Comment by hexxv** [comment]
感谢解答！ 另外请问包含沙特的城市吗

**Comment by hexxv** [comment]
非常感谢！！ @Surbowl
