### ISSUE TITLE
塞尔维亚的GeoJSON数据并没有包含科索沃地区

### ISSUE THREAD

**Issue by yogwang** [Surbowl/world-geo-json-zh#17]
塞尔维亚的GeoJSON数据并没有包含科索沃地区，科沃斯地区在项目中是单独的一个国家。

虽然科索沃宣布了独立，并且获得了一部分国家的认可，但是中国并没有承认其独立。
-  [塞尔维亚国家概况](https://www.mfa.gov.cn/web/gjhdq_676201/gj_676203/oz_678770/1206_679642/1206x0_679644/) 

如果该项目是为了简体中文用户使用的，塞尔维亚应当包含科索沃地区。

-----
这个问题是在演示项目时被塞尔维亚的客户“指正”了项目展示的塞尔维亚地图信息中缺失了科索沃地区。
该问题属于是国家主权问题还是比较严重的。

**Comment by Surbowl** [comment]
[yogwang](https://github.com/yogwang) 您好
感谢您的反馈，这一反馈非常重要，目前 master 已合并您的 [PR](https://github.com/Surbowl/world-geo-json-zh/pull/18)，并在 [v2.1.4](https://github.com/Surbowl/world-geo-json-zh/releases/tag/v2.1.4) 中发布
