### ISSUE TITLE
没有新加坡

### ISSUE THREAD

**Issue by mwj610** [Surbowl/world-geo-json-zh#3]

**Comment by Surbowl** [comment]
感谢您的反馈
我注意到[在 Natural Earth 发布的 1:110m 比例地图中，面积过小的国家或地区被省略了](https://github.com/datasets/geo-boundaries-world-110m/issues/1)
因此在 https://github.com/Surbowl/world-geo-json-zh/commit/0b4f1a2e327710547042fb1fec83ebbe4dc39e91 中我手动添加了新加坡，修复了此问题
