### ISSUE TITLE
希望能提供查询 ISO3166 数据方法

### ISSUE THREAD

**Issue by tonytony2020** [Surbowl/world-geo-json-zh#4]
类似 https://github.com/richorama/country-code-lookup
"CN" => China region info 
但 country-code-lookup 包缺中文，如 "CN" => "中国"/"中国大陆"

**Comment by Surbowl** [comment]
您好，world-geo-json-zh 是一个 JSON 格式的地图数据集，本身并不提供查询数据的 API，但是您可以将他改造为您需要的数据，下面是一个简单的例子。

```
// 加载 https://raw.githubusercontent.com/Surbowl/world-geo-json-zh/main/world.zh.json
var data = loadData();

var props = data.features.map(a => a.properties);
var info = props.find(c => c.iso_a2 === 'CN');
console.log(info);
```
