### ISSUE TITLE
关于名称更正

### ISSUE THREAD

**Issue by qingfengai** [Surbowl/world-geo-json-zh#7]
马恩岛，又译“曼岛“（英语：Isle of Man），经检索，在中国普遍是译为：马恩岛，建议更正一下常用名称

**Comment by Surbowl** [comment]
[qingfengai](https://github.com/qingfengai) 您好！
感谢您多次贡献宝贵的建议，该 Issue 已被采纳，通过 Commit https://github.com/Surbowl/world-geo-json-zh/commit/1b992c75d33a2b400fff07ac50692a176844752f 修复后在 [v2.0.2 Release](https://github.com/Surbowl/world-geo-json-zh/releases/tag/v2.0.2) 中发行

附
参考文档
[1] [国家税务总局](http://www.chinatax.gov.cn/). [中华人民共和国政府和马恩岛政府关于税收情报交换的协定](http://www.chinatax.gov.cn/n810341/n810770/c1152723/content.html).
