### ISSUE TITLE
藏南地区国界问题

### ISSUE THREAD

**Issue by F1reDiamond** [Surbowl/world-geo-json-zh#8]
藏南地区的国界有问题，这样的话地图在很多地方都用不了。
![IMG_6892](https://github.com/Surbowl/world-geo-json-zh/assets/116505172/53bf7020-0896-49ee-81ee-7ad7869d1fbd)
如果可以的话可以修复一下吗？正好新的地图标准已经出了。

**Comment by Surbowl** [comment]
[F1reDiamond](https://github.com/F1reDiamond) 你好，感谢你的宝贵建议！

目前通过参考高德地图，重新绘制了中国藏南地区的国界，并增加南海海域十段线，详见 https://github.com/Surbowl/world-geo-json-zh/commit/b02ce835d0ce2d53a133e10525d2bfde5417a601
请更新至新发布的 [v2.1.0](https://github.com/Surbowl/world-geo-json-zh/releases/tag/v2.1.0) 

关于 2023 年版标准地图，目前自然资源部官网仅提供了 JPG 与 EPS 格式，转为 GeoJson 需要一段时间，我会持续关注，并抽空用新版地图更新本项目。
