### ISSUE TITLE
能提供没有经过 mapshaper 压缩后的版本吗？

### ISSUE THREAD

**Issue by yswang0927** [Surbowl/world-geo-json-zh#9]
您好，这个更新太好了，但是发现经过 mapshaper 压缩到10%后，精度有点太低了，能提供下未经 mapshaper 压缩的版本吗？我想自己使用 mapshaper 压缩到需要的精度版本。

谢谢

**Comment by Surbowl** [comment]
您好，这份文件是将 Natural Earth [1:50m Cultural Vectors Admin 0 – Countries](https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/) 的 SHP 地图转 GeoJSON 文件后，先进行压缩，然后在压缩过的文件上参照国标地图对黑瞎子岛、藏南地区、中国台湾等边界进行调整，并添加南海十段线。

因此未压缩的版本没有调整上述边界，存在政策风险，不建议使用，如果您切实需要，可以留下邮箱，我发送给您。

**Comment by yswang0927** [comment]
好的，谢谢。
